### PR TITLE
Try/Except handling for Python modules.

### PR DESCRIPTION
**Pull request by jaredestroud**
Added try/except for handling python imports.

### CODE REVIEW

**Comment by zmallen** [comment]
I understand using try/except around imports, but isnt this strategy used for platform specific imports and libraries? Also, an import error is thrown with the specific line/offender without these try/excepts. Why catch it and print only a small message?

**Comment by jaredestroud** [comment]
Given that your requirements.txt has several additional non-standard
libraries I thought this would aid in trouble shooting issues from
individuals whom did not run pip install -r requirements.txt

I believe the message being printed is adequate enough to inform the user
of the problem. What message would you prefer be printed instead?

On Fri, May 13, 2016 at 4:49 PM, Zack Allen <notifications@github.com>
wrote:

> I understand using try/except around imports, but isnt this strategy used
> for platform specific imports and libraries? Also, an import error is
> thrown with the specific line/offender without these try/excepts. Why catch
> it and print only a small message?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fastly/ftw/pull/20#issuecomment-219155571>
>



-- 
Jared E. Stroud
Maker of things, breaker of bits.

**Comment by zmallen** [comment]
Doesnt the error message that you catch produce enough information if it goes all the way up the stack? Just seems like extraneous code to me

**Comment by jaredestroud** [comment]
I believe this is called failing gracefully.

**Comment by zmallen** [comment]
I believe if a user runs into a situation where they dont contain the libraries that they need to import, its because they didnt follow the setup instructions. The code here does essentially the same thing as python when it fails to find a library, it just adds an extra step. Im going to close this for now unless something else comes up where we require it.

**Pull request closed without merging**
