### PR TITLE
Adds port and protocol command line options

### PR DESCRIPTION
**Pull request by bclodius**
This PR supports port and protocol command line options to easily reuse large test suites without having to modify all the yaml files.

@csanders-git @zmallen

### CODE REVIEW

**Comment by zmallen** [comment]
hi there!

Thanks for the commit. Ill be looking into this today/tomorrow. Dont worry about travis failing -- those tests are fixed in a separate P/R

**Comment by bclodius** [comment]
@zmallen thanks! Looking forward to your review/feedback.

**Comment by zmallen** [comment]
this is blocked by #84 which @csanders-git *should* be merging tonight (nudge nudge). I'll ping on here for you to rebase with master once #84 is merged then tests should pass.

**Comment by zmallen** [comment]
hi @bclodius can you rebase with master? ill merge this in and do a pip release tonight

**Comment by bclodius** [comment]
@zmallen due to a mistake on my side with git history; I'll resubmit this on another PR.

**Comment by zmallen** [comment]
ACK, thx

**Pull request closed without merging**
